import '@/app/globals.css'
import BasicPageLayout from '@/components/common/basic'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Page',
  description: 'Generated by croo12',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BasicPageLayout>
          {children}
        </BasicPageLayout>
      </body>
    </html>
  )
}
